-- create_vss_videos_table.sql
-- vss_videos 테이블 생성 스크립트

-- 기존 테이블이 있다면 삭제 (선택사항, 개발 환경에서만 사용 권장)
-- DROP TABLE IF EXISTS vss_videos;

CREATE TABLE vss_videos (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(500) NOT NULL,
    FILE_SIZE BIGINT,
    FILE_URL VARCHAR(500) NOT NULL,
    WIDTH INT,
    HEIGHT INT,
    DURATION FLOAT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES vss_user(ID) ON DELETE CASCADE,
    INDEX idx_user_id (USER_ID),
    INDEX idx_created_at (CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

