CREATE TABLE `vss_videos` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`USER_ID` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`VIDEO_ID` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`FILE_NAME` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`FILE_PATH` VARCHAR(500) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`FILE_SIZE` BIGINT(20) NULL DEFAULT NULL,
	`FILE_URL` VARCHAR(500) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`WIDTH` INT(11) NULL DEFAULT NULL,
	`HEIGHT` INT(11) NULL DEFAULT NULL,
	`DURATION` FLOAT NULL DEFAULT NULL,
	`CREATED_AT` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
	`UPDATED_AT` TIMESTAMP NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `idx_user_id` (`USER_ID`) USING BTREE,
	INDEX `idx_created_at` (`CREATED_AT`) USING BTREE,
	INDEX `idx_video_id` (`VIDEO_ID`) USING BTREE,
	INDEX `idx_videos_user_id` (`USER_ID`) USING BTREE,
	INDEX `idx_videos_user_filename` (`USER_ID`, `FILE_NAME`) USING BTREE,
	INDEX `idx_videos_created_at` (`CREATED_AT`) USING BTREE,
	INDEX `idx_videos_via_video_id` (`VIDEO_ID`) USING BTREE,
	CONSTRAINT `vss_videos_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `vss_user` (`ID`) ON UPDATE RESTRICT ON DELETE CASCADE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=208
;
