CREATE TABLE `vss_reports` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`USER_ID` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`TITLE` VARCHAR(500) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`DESCRIPTION` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`CONTENT` LONGTEXT NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`WORD_COUNT` INT(11) NULL DEFAULT '0',
	`VIDEO_IDS` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`VIDEO_TITLES` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`CREATED_AT` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
	`UPDATED_AT` TIMESTAMP NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `idx_user_id` (`USER_ID`) USING BTREE,
	INDEX `idx_created_at` (`CREATED_AT`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4
;
